### ISSUE TITLE
GET:slides

### ISSUE THREAD

**Issue by alter334** [traP-jp/h24s_04_backend#11]
- ジャンル、タイトル、posted_atの3つのソート順のどれであるかをqueryparamで取る 命名はそちらに任せます
- responseで検索対象のslides

**Comment by noya2ruler** [comment]
ページは何を表すものですか？

1 ページに表示するスライド数など？（その場合は、返すスライドの個数の上限が指定されていると思えば良い？）

**Comment by alter334** [comment]
ページについては(特にフロントエンド側と関わりが強くなってくるのですが)返すスライドの上限が指定されているという認識で大丈夫です
(例えば1ページに20スライドずつでpage=2なら(1-indexedとして)条件を満たすスライドのうち21~40番目を返すという感じです)

**Comment by alter334** [comment]
ジャンル、タイトル、posted_atのソート順の3つをqueryparamで取るって意味でした 凄い読み間違いをしました:sorry:
(オフセットももしあれば追加しても良さそう)
