### ISSUE TITLE
POST:slides

### ISSUE THREAD

**Issue by alter334** [traP-jp/h24s_04_backend#12]
- var slide *model.Slide とctx.Bind(slide)してくれれば
- responseでpostしたslideを返す
- (エンドポイント実装の中で一番骨を折る作業かな(単調な作業多め))

**Comment by mehm8128** [comment]
できればBOTでtraQに通知飛ばしたい

**Comment by noya2ruler** [comment]
> できればBOTでtraQに通知飛ばしたい

別 issue に移動します
